# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=50)),
                ('jobExperience', models.FloatField()),
                ('salary', models.IntegerField()),
                ('progLang', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='downloads/')),
            ],
        ),
    ]
